name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    env:
      KEY_VAL: ${{ secrets.key_val }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.deploy }}
